---
name: snapcast-server
version: 0.26.0
slug: snapserver
description: Snapcast Server Add-on
codenotary: spiroc@gmail.com
url: https://github.com/spiro-c/ha-addons/
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: true
webui: http://[HOST]:[PORT:1780]
map: ["share:rw"]
audio: true
init: false
options:
  streams: "source = spotify:///librespot?name=Spotify&bitrate=320&devicename=HASnapcast"
  buffer: 1000
  codec: "flac"
  send_to_muted: "false"
  sampleformat: "48000:16:2"
  http_enabled: "true"
  tcp_enabled: "true"
  logging_enabled: "true"
  server_threads: -1
  server_datadir: "/usr/share/snapserver/snapweb"
schema:
  streams: str
  buffer: int
  codec: str
  send_to_muted: str
  sampleformat: str
  http_enabled: str
  tcp_enabled: str
  logging_enabled: str
  server_threads: int
  server_datadir: str
  stream_bis: str?
  stream_ter: str?
ports:
  1704/tcp: 1704
  1705/tcp: 1705
  1780/tcp: 1780
  4953/tcp: 4953
ports_description:
  1704/tcp: Client connection port
  1705/tcp: Client connection port
  1780/tcp: Web Interface Port
  4953/tcp: Tcp stream port
image: "ghcr.io/spiro-c/{arch}-addon-snapserver"