---
name: Snapcast-Client
version: 0.26.0
slug: snapclient
description: Snapcast client Add-on
codenotary: spiroc@gmail.com
url: https://github.com/spiro-c/ha-addons/
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
audio: true
init: false
options:
  host: snapserver
schema:
  host: str
image: "ghcr.io/spiro-c/{arch}-addon-snapclient"